base_config: dqn_basic
env_name: LunarLander-v2
exp_name: dqn_target_5000
hidden_size: 256
num_layers: 2
learning_rate: 0.001
total_steps: 500000
discount: 0.99
target_update_period: 5000
use_double_q: true
learning_starts: 20000
batch_size: 64
